"""add_categoria_table

Revision ID: 6907790a86c4
Revises: f24dfe0b1b37
Create Date: 2026-05-07 17:18:52.611417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6907790a86c4'
down_revision: Union[str, None] = 'f24dfe0b1b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categoria_nombre'), 'categoria', ['nombre'], unique=True)
    op.alter_column('estado_pedido', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_constraint(op.f('estado_pedido_nombre_key'), 'estado_pedido', type_='unique')
    op.create_index(op.f('ix_estado_pedido_nombre'), 'estado_pedido', ['nombre'], unique=True)
    op.create_index(op.f('ix_forma_pago_nombre'), 'forma_pago', ['nombre'], unique=True)
    op.alter_column('rol', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_constraint(op.f('rol_nombre_key'), 'rol', type_='unique')
    op.create_index(op.f('ix_rol_nombre'), 'rol', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rol_nombre'), table_name='rol')
    op.create_unique_constraint(op.f('rol_nombre_key'), 'rol', ['nombre'], postgresql_nulls_not_distinct=False)
    op.alter_column('rol', 'descripcion',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_forma_pago_nombre'), table_name='forma_pago')
    op.drop_index(op.f('ix_estado_pedido_nombre'), table_name='estado_pedido')
    op.create_unique_constraint(op.f('estado_pedido_nombre_key'), 'estado_pedido', ['nombre'], postgresql_nulls_not_distinct=False)
    op.alter_column('estado_pedido', 'descripcion',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_categoria_nombre'), table_name='categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###