"""add_categoria_table

Revision ID: 6907790a86c4
Revises: f24dfe0b1b37
Create Date: 2026-05-07 17:18:52.611417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6907790a86c4'
down_revision: Union[str, None] = 'f24dfe0b1b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categoria_nombre'), 'categoria', ['nombre'], unique=True)
    op.alter_column('estado_pedido', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    # Convert unnamed unique constraints (auto-named by PostgreSQL) into named
    # unique indexes.  Use IF EXISTS / IF NOT EXISTS so the migration works
    # regardless of whether the table was created directly by SQLModel (Docker)
    # or via a previous migration run (local dev).  See docker_pre_migrate.py.
    op.execute(
        'ALTER TABLE estado_pedido '
        'DROP CONSTRAINT IF EXISTS "estado_pedido_nombre_key"'
    )
    op.execute(
        'CREATE UNIQUE INDEX IF NOT EXISTS "ix_estado_pedido_nombre" '
        'ON estado_pedido (nombre)'
    )
    op.execute(
        'CREATE UNIQUE INDEX IF NOT EXISTS "ix_forma_pago_nombre" '
        'ON forma_pago (nombre)'
    )
    op.alter_column('rol', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.execute(
        'ALTER TABLE rol '
        'DROP CONSTRAINT IF EXISTS "rol_nombre_key"'
    )
    op.execute(
        'CREATE UNIQUE INDEX IF NOT EXISTS "ix_rol_nombre" '
        'ON rol (nombre)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS "ix_rol_nombre"')
    op.create_unique_constraint(op.f('rol_nombre_key'), 'rol', ['nombre'], postgresql_nulls_not_distinct=False)
    op.alter_column('rol', 'descripcion',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.execute('DROP INDEX IF EXISTS "ix_forma_pago_nombre"')
    op.execute('DROP INDEX IF EXISTS "ix_estado_pedido_nombre"')
    op.create_unique_constraint(op.f('estado_pedido_nombre_key'), 'estado_pedido', ['nombre'], postgresql_nulls_not_distinct=False)
    op.alter_column('estado_pedido', 'descripcion',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_categoria_nombre'), table_name='categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###